### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by sholladay** [xojs/stylelint-config-xo-space#1]
It appears that bumping the upstream config broke the tests.

I haven't looked into it, but presumably the assertion just needs to be updated.

Travis build: https://travis-ci.org/sindresorhus/stylelint-config-xo-space/jobs/296937155

**Comment by sindresorhus** [comment]
Weird. It only failed on Node.js 4 and passed now when I re-ran it: https://travis-ci.org/sindresorhus/stylelint-config-xo-space/jobs/296937155
